copyfiles:
	cp $(filepath) .

compile:
	@echo 'Python solution. Nothing to compile.'

run:
	python3 h04.py $(hash-file) > $(output)

list:
	ls *.py

show:
	@echo 'Showing python file h04.py'
	cat h04.py
