copyfiles:
	cp $(filepath) .

compile:
	@echo 'Python solution. Nothing to compile.'

run:
	python wine.py $(input) > $(output)

list:
	ls *.py

show:
	@echo 'Showing python file wine.py'
	cat wine.py
